# -*- coding: utf-8 -*-
"""tf__001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DgkjcC8lruUs2-j9ajSHgnCJMnmCZ8Q2
"""

import tensorflow as tf
print(tf.__version__)

scalar = tf.constant(3)
scalar

scalar.ndim

vektor = tf.constant([1,2])
vektor

vektor.ndim

matrix = tf.constant([[1,2],[3,4]])
matrix

matrix.ndim # ndim matrix'in boyutunu verir.