# -*- coding: utf-8 -*-
"""tf__002.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qis3xu55FbfbZb_N6JUCQ9fNzjkKyGos
"""

import tensorflow as tf
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images.ndim

train_images.shape

train_images.dtype

v = tf.Variable([1,2])
c = tf.constant([1,2])
v,c

v[0].assign(33)

tf.random.normal(shape=(3,2))#Random değerler üretir.(her seferinde)

tf.random.set_seed(15)#Değişmeyen rastgele değer üretir.
tf.random.normal(shape=(3,2))

tf.ones(shape=(2,9))#Sadece 1'lerden oluşan 2x9luk

tf.zeros(shape=(3,5))#Sadece 0'lardan oluşan 3x5lik tensör



