# -*- coding: utf-8 -*-
"""tf__003.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNnjhOQq8ViuX2LX7gUGq8oHfB4GjTaZ
"""

import tensorflow as tf

#Numpy array'leri Tensor'e çevirme
import numpy as np
a = np.arange(1,25, dtype=np.int32)
a

len(a)

a = tf.constant(numpy_T, shape=[2,4,3])
a